# Generated by Django 4.1.2 on 2022-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pack',
            name='products',
            field=models.ManyToManyField(to='home.products'),
        ),
    ]
