# Generated by Django 4.1.2 on 2022-11-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_alter_pack_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='products',
        ),
        migrations.AddField(
            model_name='pack',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.products'),
        ),
    ]
