# Generated by Django 4.1.2 on 2022-11-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pack_products_pack_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='products',
        ),
        migrations.AddField(
            model_name='pack',
            name='products',
            field=models.ManyToManyField(to='home.products'),
        ),
    ]
