# Generated by Django 4.1.2 on 2022-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pack_prods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='prods',
        ),
        migrations.AlterField(
            model_name='pack',
            name='products',
            field=models.ManyToManyField(related_query_name='Products', to='home.products'),
        ),
    ]
