# Generated by Django 4.1.2 on 2022-11-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_pack_prods_alter_pack_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='products',
            field=models.ManyToManyField(related_query_name='+', to='home.products'),
        ),
    ]
