# Generated by Django 4.1.2 on 2022-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_pack_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='include', to='home.products'),
        ),
    ]
