# Generated by Django 4.1.2 on 2022-12-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_user_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
