# Generated by Django 4.1.2 on 2022-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
