# Generated by Django 4.1.4 on 2022-12-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='image',
        ),
    ]
