# Generated by Django 4.1.4 on 2022-12-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_pack_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_ordered',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
